<?php
/**
 * FaceVideoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudEmotion API v1
 *
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FaceVideoTest Class Doc Comment
 *
 * @category    Class */
// * @description FaceVideo
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FaceVideoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "FaceVideo"
     */
    public function testFaceVideo()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "time_created"
     */
    public function testPropertyTimeCreated()
    {

    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {

    }

    /**
     * Test attribute "fq_avg"
     */
    public function testPropertyFqAvg()
    {

    }

    /**
     * Test attribute "fq_stddev"
     */
    public function testPropertyFqStddev()
    {

    }

    /**
     * Test attribute "frame_rate"
     */
    public function testPropertyFrameRate()
    {

    }

    /**
     * Test attribute "num_frames"
     */
    public function testPropertyNumFrames()
    {

    }

    /**
     * Test attribute "remote_location"
     */
    public function testPropertyRemoteLocation()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "status_text"
     */
    public function testPropertyStatusText()
    {

    }

    /**
     * Test attribute "status_message"
     */
    public function testPropertyStatusMessage()
    {

    }

    /**
     * Test attribute "response_id"
     */
    public function testPropertyResponseId()
    {

    }

    /**
     * Test attribute "md5"
     */
    public function testPropertyMd5()
    {

    }

    /**
     * Test attribute "length_ms"
     */
    public function testPropertyLengthMS()
    {

    }

    /**
     * Test attribute "length_s"
     */
    public function testPropertyLengthS()
    {

    }

    /**
     * Test attribute "frames_processed"
     */
    public function testPropertyFramesProcessed()
    {

    }

    /**
     * Test attribute "processing_time"
     */
    public function testPropertyProcessingTime()
    {

    }

    /**
     * Test attribute "engine_version"
     */
    public function testPropertyEngineVersion()
    {

    }

}
