<?php
/**
 * Status
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudEmotion API v1
 *
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Status Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Status implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'status';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'upload_status' => 'string',
        'privacy_status' => 'string',
        'license' => 'string',
        'embeddable' => 'string',
        'public_stats_viewable' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'upload_status' => 'uploadStatus',
        'privacy_status' => 'privacyStatus',
        'license' => 'license',
        'embeddable' => 'embeddable',
        'public_stats_viewable' => 'publicStatsViewable'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'upload_status' => 'setUploadStatus',
        'privacy_status' => 'setPrivacyStatus',
        'license' => 'setLicense',
        'embeddable' => 'setEmbeddable',
        'public_stats_viewable' => 'setPublicStatsViewable'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'upload_status' => 'getUploadStatus',
        'privacy_status' => 'getPrivacyStatus',
        'license' => 'getLicense',
        'embeddable' => 'getEmbeddable',
        'public_stats_viewable' => 'getPublicStatsViewable'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['upload_status'] = isset($data['upload_status']) ? $data['upload_status'] : null;
        $this->container['privacy_status'] = isset($data['privacy_status']) ? $data['privacy_status'] : null;
        $this->container['license'] = isset($data['license']) ? $data['license'] : null;
        $this->container['embeddable'] = isset($data['embeddable']) ? $data['embeddable'] : null;
        $this->container['public_stats_viewable'] = isset($data['public_stats_viewable']) ? $data['public_stats_viewable'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['upload_status'] === null) {
            $invalid_properties[] = "'upload_status' can't be null";
        }
        if ($this->container['privacy_status'] === null) {
            $invalid_properties[] = "'privacy_status' can't be null";
        }
        if ($this->container['license'] === null) {
            $invalid_properties[] = "'license' can't be null";
        }
        if ($this->container['embeddable'] === null) {
            $invalid_properties[] = "'embeddable' can't be null";
        }
        if ($this->container['public_stats_viewable'] === null) {
            $invalid_properties[] = "'public_stats_viewable' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['upload_status'] === null) {
            return false;
        }
        if ($this->container['privacy_status'] === null) {
            return false;
        }
        if ($this->container['license'] === null) {
            return false;
        }
        if ($this->container['embeddable'] === null) {
            return false;
        }
        if ($this->container['public_stats_viewable'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets upload_status
     * @return string
     */
    public function getUploadStatus()
    {
        return $this->container['upload_status'];
    }

    /**
     * Sets upload_status
     * @param string $upload_status 
     * @return $this
     */
    public function setUploadStatus($upload_status)
    {
        $this->container['upload_status'] = $upload_status;

        return $this;
    }

    /**
     * Gets privacy_status
     * @return string
     */
    public function getPrivacyStatus()
    {
        return $this->container['privacy_status'];
    }

    /**
     * Sets privacy_status
     * @param string $privacy_status 
     * @return $this
     */
    public function setPrivacyStatus($privacy_status)
    {
        $this->container['privacy_status'] = $privacy_status;

        return $this;
    }

    /**
     * Gets license
     * @return string
     */
    public function getLicense()
    {
        return $this->container['license'];
    }

    /**
     * Sets license
     * @param string $license 
     * @return $this
     */
    public function setLicense($license)
    {
        $this->container['license'] = $license;

        return $this;
    }

    /**
     * Gets embeddable
     * @return string
     */
    public function getEmbeddable()
    {
        return $this->container['embeddable'];
    }

    /**
     * Sets embeddable
     * @param string $embeddable 
     * @return $this
     */
    public function setEmbeddable($embeddable)
    {
        $this->container['embeddable'] = $embeddable;

        return $this;
    }

    /**
     * Gets public_stats_viewable
     * @return string
     */
    public function getPublicStatsViewable()
    {
        return $this->container['public_stats_viewable'];
    }

    /**
     * Sets public_stats_viewable
     * @param string $public_stats_viewable 
     * @return $this
     */
    public function setPublicStatsViewable($public_stats_viewable)
    {
        $this->container['public_stats_viewable'] = $public_stats_viewable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


